version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10

    # Group packages into shared PR
    groups:
      weekly-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

    ignore:
      - dependency-name: 'eslint-*'
      - dependency-name: 'eslint'
      - dependency-name: "@pact-foundation/pact"
        versions: [">=16.0.0"]

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
